# version: '3'

# networks:
#   laravel:
#     driver: bridge

# services:
#   nginx:
#     image: nginx:alpine
#     container_name: nginx
#     restart: unless-stopped
#     tty: true
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./:/var/www/app
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#       - ./nginx/ssl:/etc/nginx/ssl
#     depends_on:
#       - auth
#     networks:
#       - laravel

#   auth:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: auth
#     restart: unless-stopped
#     tty: true
#     working_dir: /var/www/app
#     volumes:
#       - ./:/var/www/app
#     ports:
#       - "9000:9000"
#     networks:
#       - laravel



version: '3'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth
    restart: unless-stopped
    tty: true
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    ports:
       - "9000:9000"
    networks:
      - laravel-network

networks:
  laravel-network:
    external: true

